app:
  domain: "example.com"
  port: "25565"
  uuid: "2584b733-9095-4bec-a7d5-62b473540f7a"
  xray-version: "26.7.11"
  hy2-version: "2.9.3"
  argo-version: "2026.7.1"
  argo-domain: ""
  argo-token: ""
  remarks-prefix: ""
